### ISSUE TITLE
#TK05 Crear Portafolio de empresa en Wordpress

### ISSUE THREAD

**Issue by MatiCrz** [MatiCrz/Proyecto-Integrador-2da-Etapa#40]

**Comment by MatNie89** [comment]
"Cómo crear una sección "Quiénes somos"

1. Haz una descripción de la empresa
Incluye un resumen del plan de negocios. Debe ser breve pues otros aspectos irán escritos en las demás secciones. Describe tus fortalezas, la perspectiva actual y el impacto que deseas generar.

2. Comparte la historia de la compañía
Cuenta cómo se fundó y quiénes formaron parte de su nacimiento. Si existe alguna anécdota divertida o memorable, no dudes en compartirla. A tus clientes les gustará conocer el proceso por el que pasó la empresa desde sus inicios hasta el presente. No olvides mencionar por qué surgió la idea de emprender el sueño.

3. Presenta a tu equipo
Presume a la gente que conforma tu compañía. Menciona sus nombres y puestos; también puedes incluir una breve semblanza de sus funciones o logros. No olvides los aspectos humanos dentro del trabajo y las vivencias memorables; esas historias conectan con la clientela.

Usa fotografías para presentarlos. Como pudiste ver en los ejemplos pasados, estas pueden ser un elemento funcional para que el consumidor conozca mejor el negocio.

4. Indica en dónde están ubicados
Facilitarles a los clientes la localización de tu empresa es importante, ya que desde un principio podrán saber dónde encontrarte. Haz una breve descripción del lugar de trabajo; si son oficinas modernas, coloridas o con un diseño atractivo vale la pena mostrarlo por medio de imágenes o de un video.

Incluye un módulo de Google Maps con la ubicación para que los usuarios que te visiten puedan trazar una ruta y lleguen sin complicaciones.

5. Comunica la misión de la empresa
Describe de forma breve y concisa qué es lo que la empresa busca lograr y cuál será el diferenciador para conseguirlo.

6. Muestra tus productos o servicios
Para lograr una descripción completa de tu empresa no olvides mencionar una de las cosas más importantes: los productos.

Si son artículos físicos, utiliza imágenes profesionales (y si tienen ficha técnica no olvides incluirla); si son servicios, describe a la perfección sus características y funciones.

Destaca las ventajas competitivas que posees y da a conocer por qué eres la mejor opción en el mercado.

7. Incluye formas de contacto
Muéstrales a tus clientes potenciales cómo pueden estar en contacto contigo, por ejemplo: teléfonos de oficina, números directos, redes sociales o correo electrónico.

**Comment by LeonardoEC** [comment]
29/9/22

Por votación grupal el nombre de la empresa será _ MountainCode_. 

Hoy se pactó una reunión a las 22:30 a la cual asistimos @MatNie89  y yo(@LeonardoEC ) nos reunimos a hacer los primeros pantallazos del portafolios de la empresa con los logos e imágenes realizados por @MatNie89 .

Decidimos seguir el esquema presentado por @MatNie89, el cual se describe en la parte superior de este comentario para usar como guía en el armado de la maqueta. Yo(@LeonardoEC) tome el desafío de ir moldeando cada uno de esos items para adaptarlos a la idea de empresa que tenemos como grupo

WordPress está siendo una herramienta muy interesante y útil, iremos informado sobre nuestros progresos

**Comment by LeonardoEC** [comment]
30/9/22

Luego de crear un esquema del portafolio, logramos dividirlo en tareas que asignaremos a integrantes del equipo, nos dividieremos en grupos de dos por cada seccion las cuale son 5

1. About us
2. Proyects
3. Offices
4. Conctacts
5. Shop

En la reunion de mañana(1/10/22 a las  15hrs) crearemos las Issues y repartiremos las tareas a los integrantes

@LeonardoEC

**Comment by MatiCrz** [comment]
@MatNie89 Mati te robo el texto para usarlo para crear la TK del "about us".
