### ISSUE TITLE
#TK07 Proyectos

### ISSUE THREAD

**Issue by MatiCrz** [MatiCrz/Proyecto-Integrador-2da-Etapa#44]
Seccion del portafolio "proyecto". se refiere a todos los proyectos que creamos como empresa. en este caso el Bootcampar.

Seguir ejemplo:
https://docs.google.com/document/d/1CJXumwEV3NQslBDmiylDn6q6y_xX8iBfApJIKJ86gjw/edit

**Comment by Pamela198713** [comment]
https://docs.google.com/document/d/1khWeCo4YFtoBqzLXkEQxaVhdcwLyn0zqkF9wXvS6iTw/edit?usp=drivesdk

Drive trabajado por Laura y Pamela
