### ISSUE TITLE
#TK09 Contactos

### ISSUE THREAD

**Issue by MatiCrz** [MatiCrz/Proyecto-Integrador-2da-Etapa#46]
Seccion contactos.

Crear email.

ejemplo:

https://docs.google.com/document/d/1CJXumwEV3NQslBDmiylDn6q6y_xX8iBfApJIKJ86gjw/edit

**Comment by MatNie89** [comment]
¿Qué características tiene una buena página de contacto?
Por lo general, las mejores páginas de contacto reúnen las siguientes características:

- Explican por qué alguien debería ponerse en contacto: además, describen cómo pueden ayudar a resolver los problemas de los 
visitantes.

- Incluyen un correo electrónico y número de teléfono: así los visitantes pueden encontrar la información que necesitan.

- Incluyen un formulario breve: muestran solo los campos necesarios que ayudarán a la empresa a comprender quién se pone en contacto con ellos.

- Incluyen una llamada a la acción: así mantienen a las personas en el sitio web y ofrecen otra opción por si no quieren completar el formulario.

- Demuestran el liderazgo intelectual de la empresa: al incluir una lista de publicaciones del blog o artículos recientes acerca de la empresa en los medios, tu formulario cumplirá con esta característica.

- Proporcionan enlaces a cuentas de redes sociales: añadir redes como Twitter, Facebook, Instagram o LinkedIn permite a los visitantes interactuar con la empresa gracias a opciones múltiples.

- Redireccionan al visitante a la página de agradecimiento: así los usuarios sabrán cuándo y cómo la empresa se pondrá en contacto con ellos.

**Comment by LeonardoEC** [comment]
6/10/22

Entre los días 4/10/22 y 5/10/22 @MatNie89, yo(@LeonardoEC ) y los compañeros @lidioguedez junto con @damianvirginillo hicimos un cambio general en el portafolio para facilitar su realización

Al día de fecha @MatNie89 y @LeonardoEC damos por completada nuestra Issue que consistió en:

- Creación de los logos y artículos de la empresa por @MatNie89 
- Creación de la portada y la división de secciones del portafolio por @LeonardoEC 
- Creación de la sección de contactos por @MatNie89 y @LeonardoEC 

Sin mas que agregar damos por completado nuestra Issue y quedamos a disposición para asistir al resto del equipo

@LeonardoEC 
@MatNie89
